[build-system]
requires = ["setuptools>=62.4.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tree-sitter-yarn-spinner"
description = "Yarn Spinner grammar for tree-sitter"
version = "0.0.5"
keywords = ["incremental", "parsing", "tree-sitter", "yarn-spinner"]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
authors = [{ name = "yuna0x0", email = "yuna@yuna0x0.com" }]
requires-python = ">=3.10"
license.text = "MIT"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/yuna0x0/tree-sitter-yarn-spinner"

[project.optional-dependencies]
core = ["tree-sitter~=0.24"]

[tool.cibuildwheel]
build = ["cp310-*", "cp311-*", "cp312-*"]
build-frontend = "build"

# https://github.com/pypa/twine/issues/1216#issuecomment-2607112540
# This is needed to avoid twine errors when uploading
[tool.setuptools]
license-files = []
